#ifndef CORETYPES_H
#define CORETYPES_H

#include "Defs.hpp"

#include "AABB.hpp"
#include "Array.hpp"
#include "Basis.hpp"
#include "Callable.hpp"
#include "Color.hpp"
#include "Dictionary.hpp"
#include "NodePath.hpp"
// #include "Object.hpp"
#include "PackedByteArray.hpp"
#include "PackedColorArray.hpp"
#include "PackedFloat32Array.hpp"
#include "PackedFloat64Array.hpp"
#include "PackedInt32Array.hpp"
#include "PackedInt64Array.hpp"
#include "PackedStringArray.hpp"
#include "PackedVector2Array.hpp"
#include "PackedVector3Array.hpp"
#include "Plane.hpp"
#include "Quat.hpp"
#include "RID.hpp"
#include "Rect2.hpp"
#include "Rect2i.hpp"
#include "Signal.hpp"
#include "String.hpp"
#include "StringName.hpp"
#include "Transform.hpp"
#include "Transform2D.hpp"
#include "Vector2.hpp"
#include "Vector2i.hpp"
#include "Vector3.hpp"
#include "Vector3i.hpp"

#include "Wrapped.hpp"

#endif // CORETYPES_H
