ANDROID_BASE_URL=http://dl.google.com/android/repository

ANDROID_NDK_RELEASE=r20
ANDROID_NDK_DIR=android-ndk
ANDROID_NDK_FILENAME=android-ndk-$ANDROID_NDK_RELEASE-linux-x86_64.zip
ANDROID_NDK_URL=$ANDROID_BASE_URL/$ANDROID_NDK_FILENAME


curl -L -O $ANDROID_NDK_URL
unzip -qq $ANDROID_NDK_FILENAME
mv android-ndk-$ANDROID_NDK_RELEASE $ANDROID_NDK_ROOT
