set( GODOTCPP_SOURCES
        src/godot.cpp
        src/classes/editor_plugin_registration.cpp
        src/classes/low_level.cpp
        src/classes/wrapped.cpp
        src/core/class_db.cpp
        src/core/error_macros.cpp
        src/core/memory.cpp
        src/core/method_bind.cpp
        src/core/object.cpp
        src/variant/aabb.cpp
        src/variant/basis.cpp
        src/variant/callable_custom.cpp
        src/variant/callable_method_pointer.cpp
        src/variant/char_string.cpp
        src/variant/color.cpp
        src/variant/packed_arrays.cpp
        src/variant/plane.cpp
        src/variant/projection.cpp
        src/variant/quaternion.cpp
        src/variant/rect2.cpp
        src/variant/rect2i.cpp
        src/variant/transform2d.cpp
        src/variant/transform3d.cpp
        src/variant/variant.cpp
        src/variant/vector2.cpp
        src/variant/vector2i.cpp
        src/variant/vector3.cpp
        src/variant/vector3i.cpp
        src/variant/vector4.cpp
        src/variant/vector4i.cpp
)
set( GODOTCPP_HEADERS
        include/godot_cpp/godot.hpp
        include/godot_cpp/classes/editor_plugin_registration.hpp
        include/godot_cpp/classes/ref.hpp
        include/godot_cpp/classes/wrapped.hpp
        include/godot_cpp/core/binder_common.hpp
        include/godot_cpp/core/builtin_ptrcall.hpp
        include/godot_cpp/core/class_db.hpp
        include/godot_cpp/core/defs.hpp
        include/godot_cpp/core/engine_ptrcall.hpp
        include/godot_cpp/core/error_macros.hpp
        include/godot_cpp/core/math.hpp
        include/godot_cpp/core/memory.hpp
        include/godot_cpp/core/method_bind.hpp
        include/godot_cpp/core/method_ptrcall.hpp
        include/godot_cpp/core/mutex_lock.hpp
        include/godot_cpp/core/object.hpp
        include/godot_cpp/core/object_id.hpp
        include/godot_cpp/core/property_info.hpp
        include/godot_cpp/core/type_info.hpp
        include/godot_cpp/templates/cowdata.hpp
        include/godot_cpp/templates/hash_map.hpp
        include/godot_cpp/templates/hash_set.hpp
        include/godot_cpp/templates/hashfuncs.hpp
        include/godot_cpp/templates/list.hpp
        include/godot_cpp/templates/local_vector.hpp
        include/godot_cpp/templates/pair.hpp
        include/godot_cpp/templates/rb_map.hpp
        include/godot_cpp/templates/rb_set.hpp
        include/godot_cpp/templates/rid_owner.hpp
        include/godot_cpp/templates/safe_refcount.hpp
        include/godot_cpp/templates/search_array.hpp
        include/godot_cpp/templates/self_list.hpp
        include/godot_cpp/templates/sort_array.hpp
        include/godot_cpp/templates/spin_lock.hpp
        include/godot_cpp/templates/thread_work_pool.hpp
        include/godot_cpp/templates/vector.hpp
        include/godot_cpp/templates/vmap.hpp
        include/godot_cpp/templates/vset.hpp
        include/godot_cpp/variant/aabb.hpp
        include/godot_cpp/variant/array_helpers.hpp
        include/godot_cpp/variant/basis.hpp
        include/godot_cpp/variant/callable_custom.hpp
        include/godot_cpp/variant/callable_method_pointer.hpp
        include/godot_cpp/variant/char_string.hpp
        include/godot_cpp/variant/char_utils.hpp
        include/godot_cpp/variant/color.hpp
        include/godot_cpp/variant/color_names.inc.hpp
        include/godot_cpp/variant/plane.hpp
        include/godot_cpp/variant/projection.hpp
        include/godot_cpp/variant/quaternion.hpp
        include/godot_cpp/variant/rect2.hpp
        include/godot_cpp/variant/rect2i.hpp
        include/godot_cpp/variant/transform2d.hpp
        include/godot_cpp/variant/transform3d.hpp
        include/godot_cpp/variant/typed_array.hpp
        include/godot_cpp/variant/variant.hpp
        include/godot_cpp/variant/vector2.hpp
        include/godot_cpp/variant/vector2i.hpp
        include/godot_cpp/variant/vector3.hpp
        include/godot_cpp/variant/vector3i.hpp
        include/godot_cpp/variant/vector4.hpp
        include/godot_cpp/variant/vector4i.hpp
)
